os: linux
dist: trusty

language: java
jdk: 
  - openjdk11

services:
  - docker

before_install:
  - chmod +x ./.travis/docker-build-and-push.sh

script: cd ./core && mvn clean package

after_success: 
  - cd .. && bash ./.travis/docker-build-and-push.sh

cache:
  directories:
  - .autoconf
  - $HOME/.m2
