version: '3'
services:
    timescaledb:
        image: timescale/timescaledb:latest-pg12
        hostname: timescaledb
        container_name: timescaledb
        volumes:
            - timescaledb_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: h4o
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    hivemq-ce:
        image: hivemq/hivemq-ce
        hostname: hivemq-ce
        container_name: hivemq
        ports:
            - "1883:1883"
    zookeeper:
        image: confluentinc/cp-zookeeper
        restart: unless-stopped
        hostname: zookeeper
        container_name: zookeeper
        ports:
        - 2181:2181
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
        volumes:
            - ./data/zookeeper/data:/data
            - ./data/zookeeper/datalog:/datalog
        restart: unless-stopped
    kafka:
        image: confluentinc/cp-kafka
        hostname: kafka
        container_name: kafka
        ports:
            - "9092:9092"
        volumes:
            - ./data/kafka/kafka-logs:/kafka.logs
            - ./kafka/create-topics.sh:/docker-entrypoint-initdb.d/create-topics.sh
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092, PLAINTEXT_LOCALHOST://localhost:9092
            KAFKA_LISTENERS: PLAINTEXT://kafka:29092, PLAINTEXT_LOCALHOST://0.0.0.0:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_LOCALHOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
        depends_on:
            - zookeeper
        restart: unless-stopped
    connector-mqtt:
        hostname: connector-mqtt
        container_name: h4o-connector-mqtt
        build:
            context: ../
            dockerfile: Dockerfile.h4o.connector.mqtt
        environment:
            - "SPRING_PROFILES_ACTIVE=docker"
        ports:
        - 8095:8095
        depends_on:
           - hivemq-ce
           - zookeeper
           - kafka
    h4o-kafka-consumer:
        hostname: h4o-kafka-consumer
        container_name: h4o-kafka-consumer
        build:
            context: ../
            dockerfile: Dockerfile.h4o.kafka.consumer
        environment:
            - "SPRING_PROFILES_ACTIVE=docker"
        ports:
        - 8385:8385
        depends_on:
           - timescaledb
           - kafka   
    mqtt-test-sensors-client:
        hostname: mqtt-test-sensors-client
        container_name: h4o-fake-sensors
        build:
            context: ../
            dockerfile: Dockerfile.h4o.mqtt.test.sensors.client
        environment:
            - "SPRING_PROFILES_ACTIVE=docker"
        ports:
        - 8096:8096
        depends_on:
           - hivemq-ce
    grafana:
        image: grafana/grafana:latest
        hostname: grafana
        container_name: grafana
        ports:
            - 3000:3000
volumes:
  timescaledb_data:
    driver: local
